ERROR - 2024-01-04 04:28:20 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'aitsun_erp_db' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'aitsun_erp_db', 3306, '', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
#7 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(4964): company('1')
#8 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Home.php(30): now_time('1')
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'aitsun_erp_db' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp2\htdocs\aitsun-erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(4964): company('1')
#7 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Home.php(30): now_time('1')
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Home->index()
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-01-04 04:28:20 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'aitsun_erp_db'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `customers`
WHERE `id` = :id:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
 6 APPPATH\Helpers\apanel_helper.php(4964): company('1')
 7 APPPATH\Controllers\Home.php(30): now_time('1')
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-04 04:28:21 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'aitsun_erp_db' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'aitsun_erp_db', 3306, '', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
#7 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(4964): company('1')
#8 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Home.php(30): now_time('1')
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'aitsun_erp_db' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp2\htdocs\aitsun-erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(4964): company('1')
#7 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Home.php(30): now_time('1')
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Home->index()
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-01-04 04:28:21 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'aitsun_erp_db'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `customers`
WHERE `id` = :id:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
 6 APPPATH\Helpers\apanel_helper.php(4964): company('1')
 7 APPPATH\Controllers\Home.php(30): now_time('1')
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
